### ISSUE TITLE
Regression: IgnorePkg cannot be overridden by manual upgrade

### ISSUE THREAD

**Issue by alexforencich** [Morganamilo/paru#394]
### Affected Version
**paru v1.7.0 - libalpm v13.0.0**

### Description
paru is currently not allowing IgnorePkg to be overridden.  Not sure if this is a new regression as of pacman 6 and the new version of libalpm, but I just noticed it today.  

Previously, if a package has been added to IgnorePkg, it can be manually installed/upgraded with paru -S/pacman -S by specifying the package name.  Currently, that does not work, and paru reports that the target is not found.  Originally I thought this was an issue with pacman 6, but pacman 6 correctly overrides ignorepkg and will install/upgrade manually specified packages.  

Output when attempting to reinstall a package that's included in ignorepkg:

    $ paru -S linux
    :: Resolving dependencies...
    error: could not find all required packages:
        linux (target)

**Comment by Morganamilo** [comment]
I believe this is the same cause as #392 so should be fixed also though I've not tried.

**Comment by alexforencich** [comment]
Okay, looks like paru was just updated to a newer version.  This time, it fails silently.  No target error, but it still doesn't install the packages.  

    $ paru -V
    paru v1.7.1 - libalpm v13.0.0
    $ paru -S linux-lts{,-headers}
    :: Resolving dependencies...
    
    Repo (2) linux-lts-5.10.42-1  linux-lts-headers-5.10.42-1
    
    :: Proceed with installation? [Y/n]: 
    $

**Comment by Morganamilo** [comment]
Post your config.

**Comment by alexforencich** [comment]
$ cat .config/paru/paru.conf 
    [options]
    SudoLoop
    Devel
    UpgradeMenu

**Comment by alexforencich** [comment]
Also, I don't know why I posted v1.4.0, this was actually an issue on v1.7.0.  I think I may have run paru -V on a different machine that's a bit out of date.  

    $ paru -V
    paru v1.7.0 - libalpm v13.0.0
    $ paru -S linux
    :: Resolving dependencies...
    error: could not find all required packages:
        linux (target)

**Comment by Morganamilo** [comment]
Yeah 1.7.0 has a bug with the question events. That was fixed in 1.7.1 which is why the error changed. There just happens to be a separate issue with it.

**Comment by alexforencich** [comment]
Ah, makes sense.

**Comment by alexforencich** [comment]
Just checked with paru-git, and it is fixed now.  Thanks for the quick turnaround!

**Comment by Morganamilo** [comment]
Added to the tests now: https://github.com/Morganamilo/paru/commit/f451df3da1e9a0d2a24576f12f07b22dc131ee29
