### ISSUE TITLE
Cannot update paru to 1.7.0-1 - alpm.rs does not support libalpm v12.0.2

### ISSUE THREAD

**Issue by ArekPiekarz** [Morganamilo/paru#398]
### Affected Version
paru v1.6.1 - libalpm v12.0.2
Manjaro 21.0.5

### Description
On Manjaro when updating packages using the `paru` command, paru tries to update itself to 1.7.0-1 and the compilation panics with an error:
`this version of alpm.rs does not support libalpm v12.0.2 only v13.x.0 is supported`
Note that when trying to update the system with pacman, no new packages are available.

### Output
```sh
$ RUST_BACKTRACE=full paru
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 sublime-text is up to date
:: Starting full system upgrade...
warning: pamac-cli: local (10.1.2-0.1) is newer than extra (10.0.6-2)
warning: pamac-common: local (10.1.2-0.1) is newer than extra (10.0.6-2)
warning: pamac-flatpak-plugin: local (10.1.2-0.1) is newer than extra (10.0.6-2)
warning: pamac-gtk: local (10.1.2-0.1) is newer than extra (10.0.6-2)
warning: pamac-snap-plugin: local (10.1.2-0.1) is newer than extra (10.0.6-2)
 there is nothing to do
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) paru-1.7.0-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: paru 1.7.0-1 (Wed Jun  2 20:24:32 2021)
==> Retrieving sources...
  -> Found paru-1.7.0.tar.gz
==> Validating source files with sha256sums...
    paru-1.7.0.tar.gz ... Passed
==> Making package: paru 1.7.0-1 (Wed Jun  2 20:24:35 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found paru-1.7.0.tar.gz
==> Validating source files with sha256sums...
    paru-1.7.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting paru-1.7.0.tar.gz with bsdtar
==> Sources are ready.
paru-1.7.0-1: parsing pkg list...
==> Making package: paru 1.7.0-1 (Wed Jun  2 20:24:43 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
   Compiling libc v0.2.95
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling autocfg v1.0.1
   Compiling syn v1.0.72
   Compiling cfg-if v1.0.0
   Compiling memchr v2.4.0
   Compiling log v0.4.14
   Compiling getrandom v0.1.16
   Compiling proc-macro-hack v0.5.19
   Compiling pin-project-lite v0.2.6
   Compiling ppv-lite86 v0.2.10
   Compiling siphasher v0.3.5
   Compiling futures-core v0.3.15
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling once_cell v1.7.2
   Compiling bytes v1.0.1
   Compiling itoa v0.4.7
   Compiling pkg-config v0.3.19
   Compiling matches v0.1.8
   Compiling futures-task v0.3.15
   Compiling cc v1.0.68
   Compiling serde_derive v1.0.126
   Compiling futures-channel v0.3.15
   Compiling futures-sink v0.3.15
   Compiling proc-macro-nested v0.1.7
   Compiling serde v1.0.126
   Compiling slab v0.4.3
   Compiling futures-io v0.3.15
   Compiling pin-utils v0.1.0
   Compiling alpm-sys v2.0.0
   Compiling fnv v1.0.7
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.34
   Compiling tinyvec_macros v0.1.0
   Compiling encoding_rs v0.8.28
   Compiling native-tls v0.2.7
   Compiling hashbrown v0.9.1
   Compiling crc32fast v1.2.1
   Compiling httparse v1.4.1
   Compiling ryu v1.0.5
   Compiling percent-encoding v2.1.0
   Compiling openssl-probe v0.1.4
   Compiling try-lock v0.2.3
   Compiling new_debug_unreachable v1.0.4
   Compiling adler v1.0.2
   Compiling tower-service v0.3.1
   Compiling mac v0.1.1
   Compiling precomputed-hash v0.1.1
   Compiling httpdate v1.0.1
   Compiling serde_json v1.0.64
   Compiling async-trait v0.1.50
   Compiling dtoa v0.4.8
   Compiling utf-8 v0.7.6
   Compiling regex-syntax v0.6.25
   Compiling convert_case v0.4.0
   Compiling base64 v0.13.0
   Compiling nodrop v0.1.14
   Compiling stable_deref_trait v1.2.0
   Compiling smallvec v1.6.1
   Compiling mime v0.3.16
   Compiling byteorder v1.4.3
   Compiling ipnet v2.3.0
   Compiling cini v0.1.1
   Compiling anyhow v1.0.40
   Compiling remove_dir_all v0.5.3
   Compiling thin-slice v0.1.1
   Compiling humantime v2.1.0
   Compiling number_prefix v0.4.0
   Compiling termcolor v1.1.2
   Compiling srcinfo v1.0.0
   Compiling htmlescape v0.3.1
   Compiling ansi_term v0.12.1
   Compiling tracing-core v0.1.18
   Compiling phf_shared v0.8.0
   Compiling futures-macro v0.3.15
   Compiling tokio v1.6.1
   Compiling futures-util v0.3.15
   Compiling indexmap v1.6.2
   Compiling miniz_oxide v0.4.4
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling unicode-bidi v0.3.5
   Compiling http v0.2.4
   Compiling foreign-types v0.3.2
   Compiling tinyvec v1.2.0
   Compiling form_urlencoded v1.0.1
   Compiling futf v0.1.4
   Compiling dtoa-short v0.3.3
   Compiling openssl-sys v0.9.63
   Compiling servo_arc v0.1.1
   Compiling pacmanconf v1.0.0
   Compiling fxhash v0.2.1
   Compiling tracing v0.1.26
   Compiling tendril v0.4.2
   Compiling want v0.3.0
   Compiling unicode-normalization v0.1.18
   Compiling aho-corasick v0.7.18
   Compiling bstr v0.2.16
   Compiling quote v1.0.9
   Compiling http-body v0.4.2
   Compiling mio v0.7.11
   Compiling signal-hook-registry v1.3.0
   Compiling num_cpus v1.13.0
   Compiling socket2 v0.4.0
   Compiling getrandom v0.2.3
   Compiling terminal_size v0.1.17
   Compiling dirs-sys v0.3.6
   Compiling atty v0.2.14
   Compiling time v0.1.44
   Compiling term_size v0.3.2
   Compiling nix v0.20.0
   Compiling alpm v2.0.0
   Compiling regex v1.5.4
   Compiling quick-xml v0.20.0
   Compiling idna v0.2.3
   Compiling rand_core v0.5.1
   Compiling rand_core v0.6.2
   Compiling console v0.14.1
   Compiling dirs v3.0.2
   Compiling flate2 v1.0.20
error: failed to run custom build command for `alpm v2.0.0`

Caused by:
  process didn't exit successfully: `/home/user/.cache/paru/clone/paru/src/paru-1.7.0/target/release/build/alpm-e4058bce6d1c07dd/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'this version of alpm.rs does not support libalpm v12.0.2 only v13.x.0 is supported', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/alpm-2.0.0/build.rs:18:9
  stack backtrace:
     0:     0x555cb4291290 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0x555cb4291290 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x555cb4291290 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x555cb4291290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x555cb42a748f - core::fmt::write::h3b84512577ca38a8
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
     5:     0x555cb428fd42 - std::io::Write::write_fmt::h465f8feea02e2aa1
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
     6:     0x555cb4292f35 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x555cb4292f35 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x555cb4292f35 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
     9:     0x555cb42929e3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
    10:     0x555cb429353d - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
    11:     0x555cb42930d7 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
    12:     0x555cb429174c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
    13:     0x555cb4293039 - rust_begin_unwind
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
    14:     0x555cb4275e1b - std::panicking::begin_panic_fmt::h400b8e9dca200408
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
    15:     0x555cb427a174 - build_script_build::main::hf91c25e605037092
    16:     0x555cb4279bf3 - core::ops::function::FnOnce::call_once::h7db65b66dd839782
    17:     0x555cb4279b09 - std::sys_common::backtrace::__rust_begin_short_backtrace::h597253f15ad004ba
    18:     0x555cb4279829 - std::rt::lang_start::{{closure}}::hd9e01cd8d0af90c8
    19:     0x555cb429393a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
    20:     0x555cb429393a - std::panicking::try::do_call::h10b0bd4879c8dfb0
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
    21:     0x555cb429393a - std::panicking::try::h60c6780d33419e92
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
    22:     0x555cb429393a - std::panic::catch_unwind::h111f33e08c52e2ce
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
    23:     0x555cb429393a - std::rt::lang_start_internal::h126f2e09345dbfda
                                 at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
    24:     0x555cb4279811 - std::rt::lang_start::hfaf19efb33517095
    25:     0x555cb427a243 - main
    26:     0x7fb6a32f5b25 - __libc_start_main
    27:     0x555cb427679e - _start
    28:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
    Aborting...
:: Packages failed to build: paru-1.7.0-1
```

```sh
$ LC_ALL=C sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 sublime-text is up to date
:: Starting full system upgrade...
warning: pamac-cli: local (10.1.2-0.1) is newer than extra (10.0.6-2)
warning: pamac-common: local (10.1.2-0.1) is newer than extra (10.0.6-2)
warning: pamac-flatpak-plugin: local (10.1.2-0.1) is newer than extra (10.0.6-2)
warning: pamac-gtk: local (10.1.2-0.1) is newer than extra (10.0.6-2)
warning: pamac-snap-plugin: local (10.1.2-0.1) is newer than extra (10.0.6-2)
 there is nothing to do
```

**Comment by ECon87** [comment]
Exact same problem with me

**Comment by nylonicious** [comment]
You will need to wait for Manjaro to update `pacman` to 6.0. `pacman 6.0` provides `libalpm 13.0.0` and the [alpm](https://github.com/archlinux/alpm.rs) supports now only version 13.x.0

**Comment by ECon87** [comment]
> You will need to wait for Manjaro to update `pacman` to 6.0. `pacman 6.0` provides `libalpm 13.0.0` and the [alpm](https://github.com/archlinux/alpm.rs) since v2.0 supports now only version 13.x.0

Thank you.

**Comment by HoolaBoola** [comment]
Would it be a good idea to edit the PKGBUILD to depend on Pacman version 6.0 or higher?

More specific - `depends=('git' 'pacman')` to `depends=('git' 'pacman>=6.0')` if I understood  PKGBUILD syntax correctly.

**Comment by Lynnesbian** [comment]
Somewhat off topic, but you can search for `pacman` on [Manjaro's "branch compare" page](https://manjaro.org/branch-compare/) to check what pacman version they have packaged.

Currently, the Testing and Unstable stream's versions are both on `6.0.0-1` while stable is on `5.2.2-6`, so if you're using Manjaro Testing/Unstable, you should be able to update paru now. If you're on Stable, you'll need to wait a little longer - I'm not sure if/where the Manjaro team maintain information about package versioning, but I assume now that it's gone through both Unstable and Testing, Stable should be soon to follow.

**Comment by PowerUser64** [comment]
I got into a situation where the version of `libalpm.so` that `paru` wanted was 12, but I had version 13 installed, so I had to manually clone the repo and update.

**Comment by ArekPiekarz** [comment]
Manjaro now ships with pacman 6 and newer version of libalpm, so the issue is now fixed.

**Comment by PrismaPhonic** [comment]
I have pacman 6 and this is still broken @PowerUser64 what did you manually clone exactly? I've already tried building paru off master after a full wipe and hit exactly this problem.

**Comment by mculp** [comment]
yeah, none of this works for me

```
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: `"pkg-config" "--libs" "--cflags" "libalpm" "libalpm >= 13.0.0"` did not exit successfully: exit status: 1
  error: could not find system library 'libalpm' required by the 'alpm-sys' crate
```

```
$ pacman --version
.--.                  Pacman v6.0.1 - libalpm v13.0.1
```

Also tried installing via cargo as @PrismaPhonic suggested
