### ISSUE TITLE
Package providers printed in random order on each run

### ISSUE THREAD

**Issue by nyanpasu64** [Morganamilo/paru#524]
### Affected Version
**paru -V**: paru v1.8.2 - libalpm v13.0.0

### Description
When I repeatedly run a `paru -S` command where either the original package or a dependency has multiple AUR providers, the providers are printed in a random order each time.

**Have you checked previous issues?** yes

### Output
**Include the FULL output of any relevant commands/configs**

**Don't cut parts of the input always include the FULL thing**

**paru.conf and pacman.conf are usually always relevant**: [pacman.conf](https://github.com/Morganamilo/paru/files/7078849/pacman.conf.txt), bug occurs with paru.conf renamed.

```
nyanpasu64@ryzen ~ [SIGINT]> paru -S kwinft-git
:: Resolving dependencies...
:: There are 2 providers available for wrapland:
:: Repository AUR:
    1) wrapland-git  2) wrapland-kwinft  
Enter a number (default=1): 
:: There are 2 providers available for disman:
:: Repository AUR:
    1) disman-kwinft  2) disman-git  
Enter a number (default=1): ^C⏎
nyanpasu64@ryzen ~ [SIGINT]> paru -S kwinft-git
:: Resolving dependencies...
:: There are 2 providers available for wrapland:
:: Repository AUR:
    1) wrapland-kwinft  2) wrapland-git  
Enter a number (default=1): 
:: There are 2 providers available for disman:
:: Repository AUR:
    1) disman-git  2) disman-kwinft  
Enter a number (default=1): ^C⏎
```

The same issue occurs when I repeatedly run `paru -S wrapland`. For some reason, `paru -S paru` and `paru -S nheko` comes with a consistent order, possibly because there's one package with the same name as entered, followed by 1 or 2 alternative packages. I'm not sure if `paru` and `nheko` come first because they're lexicographically first or because they're an exact string match.

**Comment by Morganamilo** [comment]
Should be fixed in https://github.com/Morganamilo/aur-depends/commit/b9dc3b77afc6eee1e94a519fee064ebdb925de14

**Comment by nyanpasu64** [comment]
How do I test the fix? `paru -S paru-git` isn't fixed and doesn't seem to pick up that repo.

**Comment by Morganamilo** [comment]
It'll be fixed when I push a new release of aur-dopends. This is a miner thing so won't be for a while.
